language: node_js
node_js:
  - "4.4.2"
  - "4"
  - "5"

script:
  - "node `npm bin`/jshint index.js src"
  - "node `npm bin`/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- --recursive && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"
